[project]
name = "osu-bpm-tap"
version = "0.1.0"
description = "Osu tapping bpm training"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyboard>=0.13.5",
    "sshkeyboard>=2.3.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
    "ruff>=0.15.14",
    "ty>=0.0.39",
]
